# [Docker for Linux](https://docs.solace.com/Solace-SW-Broker-Set-Up/Docker-Containers/Set-Up-Single-Linux-Container.htm)
- name: Upload the PubSub+ Image
  copy:
    src: "{{solace_docker_image_full_path}}"
    dest: /tmp/PUBSUB_DOCKER
  when: solace_docker_image_full_path is defined

- name: Load the image into Docker
  shell: docker load -i /tmp/PUBSUB_DOCKER
  when: solace_docker_image_full_path is defined

- name: Pull the Solace PubSub+ standard image
  shell: docker pull solace/solace-pubsub-standard
  when: solace_docker_image_full_path is undefined
